create table if not exists public.books (
  id bigint generated by default as identity primary key,
  title text not null,
  author text not null,
  category text not null,
  description text not null default '',
  publication_year integer not null,
  isbn text not null default '',
  cover_url text not null default '',
  purchase_url text not null default '',
  published boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists idx_books_publicados on public.books (published, publication_year desc);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  protocol text not null unique,
  author_name text not null,
  email text not null,
  phone text not null default '',
  biography text not null,
  title text not null,
  subtitle text not null default '',
  category text not null,
  synopsis text not null,
  audience text not null,
  differentiator text not null,
  stage text not null,
  word_count text not null default '',
  rights_confirmed boolean not null check (rights_confirmed = true),
  cover_available boolean not null default false,
  reviewer_one text not null default '',
  reviewer_two text not null default '',
  notes text not null default '',
  status text not null default 'recebida',
  created_at timestamptz not null default now()
);
create index if not exists idx_submissions_status_data on public.submissions (status, created_at desc);

alter table public.books enable row level security;
alter table public.submissions enable row level security;
drop policy if exists "catalogo_publico_leitura" on public.books;
create policy "catalogo_publico_leitura" on public.books for select to anon using (published = true);
drop policy if exists "propostas_publicas_insercao" on public.submissions;
create policy "propostas_publicas_insercao" on public.submissions for insert to anon with check (rights_confirmed = true and status = 'recebida');

grant select on public.books to anon;
grant insert on public.submissions to anon;
revoke select, update, delete on public.submissions from anon;
